# Numpy 기초연습문제

In [3]:
import numpy as np

## np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.¶

In [4]:
a = np.zeros((3, 4)) # zeros를 이용하면, 모든 요소값이 0인 ndarray를 만들 수 있다. 앞이 행, 뒤가 열이다.
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

In [5]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] = i*4 + j + 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [6]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num
        num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

## 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [7]:
a[1, 2]

7.0

## a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

In [8]:
a.shape


(3, 4)

In [9]:
a[[1], :]

array([[5., 6., 7., 8.]])

## a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

In [10]:
a[:,[0, 2]]

array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.]])

## 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.

In [11]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result

array([1., 2., 3., 4., 5., 6.])

In [12]:
a[a <= 6]

array([1., 2., 3., 4., 5., 6.])

## np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.¶

In [13]:
b = np.random.random((3, 4))
b

array([[0.14877578, 0.49537578, 0.82983138, 0.08198622],
       [0.97245974, 0.44030565, 0.20668166, 0.40159793],
       [0.81553875, 0.70561176, 0.82333996, 0.97806773]])

## a와 b의 요소곱을 하여 c에 저장하시오.

In [14]:
c = a * b
c

array([[ 0.14877578,  0.99075155,  2.48949415,  0.3279449 ],
       [ 4.8622987 ,  2.64183392,  1.44677162,  3.21278343],
       [ 7.33984872,  7.05611758,  9.05673958, 11.73681274]])

## b의 전치행렬을 구하여 d에 저장하시오.

In [15]:
d = b.T
d

array([[0.14877578, 0.97245974, 0.81553875],
       [0.49537578, 0.44030565, 0.70561176],
       [0.82983138, 0.20668166, 0.82333996],
       [0.08198622, 0.40159793, 0.97806773]])

In [17]:
d.shape

(4, 3)

## a와 d에 대하여 각 차원의 크기를 출력하시오.

In [18]:
print(a.shape, d.shape) # shpae 함수 쓰면 차원의 크기를 알 수 있다.

(3, 4) (4, 3)


## a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [20]:
e = a.dot(d) # dot을 사용해야 행렬의 곱을 할 수 있다.
e

array([[ 3.95696637,  4.07950774,  8.60905306],
       [10.18084301, 12.16368767, 21.89928584],
       [16.40471965, 20.2478676 , 35.18951862]])

## e에 대하여 각 열의 합을 계산하시오.

In [21]:
np.sum(e, axis=1) # 열의 합을 구하려면 axis = 1 이 반드시 있어야 한다.

array([16.64552717, 44.24381652, 71.84210586])